### ISSUE TITLE
"unresolved node modules" when webpack attempts to package as dependency

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoind-ha#14]
I know this is supposed to be optional, not sure if something else is needed for webpack

```
Error: Unresolved node modules: @pm2/io
    at /home/ender/Code/proton/node_modules/app-builder-lib/src/util/packageDependencies.ts:112:21
From previous event:
    at Collector.resolveUnresolvedHoisted (/home/ender/Code/proton/node_modules/app-builder-lib/src/util/packageDependencies.ts:88:81)
    at /home/ender/Code/proton/node_modules/app-builder-lib/src/util/packageDependencies.ts:83:18
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Collector.collect (/home/ender/Code/proton/node_modules/app-builder-lib/src/util/packageDependencies.ts:76:28)
    at /home/ender/Code/proton/node_modules/app-builder-lib/src/util/packageDependencies.ts:47:44
    at Generator.next (<anonymous>)
From previous event:
    at _getProductionDependencies (/home/ender/Code/proton/node_modules/app-builder-lib/out/util/packageDependencies.js:92:37)
    at getProductionDependencies (/home/ender/Code/proton/node_modules/app-builder-lib/out/util/packageDependencies.js:83:37)
    at Lazy.<anonymous> (/home/ender/Code/proton/node_modules/app-builder-lib/src/util/packageDependencies.ts:41:25)
    at Lazy.get value [as value] (/home/ender/Code/proton/node_modules/lazy-val/src/main.ts:18:25)
    at /home/ender/Code/proton/node_modules/app-builder-lib/out/util/yarn.js:166:90
    at Generator.next (<anonymous>)
From previous event:
    at _rebuild (/home/ender/Code/proton/node_modules/app-builder-lib/src/util/yarn.ts:179:5)
    at rebuild (/home/ender/Code/proton/node_modules/app-builder-lib/out/util/yarn.js:163:19)
    at /home/ender/Code/proton/node_modules/app-builder-lib/src/util/yarn.ts:20:11
From previous event:
    at _installOrRebuild (/home/ender/Code/proton/node_modules/app-builder-lib/out/util/yarn.js:71:28)
    at installOrRebuild (/home/ender/Code/proton/node_modules/app-builder-lib/out/util/yarn.js:55:28)
    at /home/ender/Code/proton/node_modules/electron-builder/src/cli/install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at _installAppDeps (/home/ender/Code/proton/node_modules/electron-builder/out/cli/install-app-deps.js:176:26)
    at installAppDeps (/home/ender/Code/proton/node_modules/electron-builder/out/cli/install-app-deps.js:144:26)
    at then (/home/ender/Code/proton/node_modules/electron-builder/src/cli/cli.ts:46:19)
error Command failed with exit code 1.
```

**Comment by brandonlehmann** [comment]
This package does not support webpack and never will.
