### ISSUE TITLE
dam i had this issue before and i cant figure out how i beat it......

### ISSUE THREAD

**Issue by DrBlackross** [turtlecoin/turtlecoind-ha#15]
node service.js 
internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/drblackross/turtlecoind-ha/node_modules/node-pty/lib/utils.js
- /home/drblackross/turtlecoind-ha/node_modules/node-pty/lib/unixTerminal.js
- /home/drblackross/turtlecoind-ha/node_modules/node-pty/lib/index.js
- /home/drblackross/turtlecoind-ha/index.js
- /home/drblackross/turtlecoind-ha/service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.loadNative (/home/drblackross/turtlecoind-ha/node_modules/node-pty/lib/utils.js:22:16)
    at Object.<anonymous> (/home/drblackross/turtlecoind-ha/node_modules/node-pty/lib/unixTerminal.js:24:19)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/drblackross/turtlecoind-ha/node_modules/node-pty/lib/utils.js',
    '/home/drblackross/turtlecoind-ha/node_modules/node-pty/lib/unixTerminal.js',
    '/home/drblackross/turtlecoind-ha/node_modules/node-pty/lib/index.js',
    '/home/drblackross/turtlecoind-ha/index.js',
    '/home/drblackross/turtlecoind-ha/service.js'

someone on discord posted a link, and now i can't search for it (for some odd reason)

drblackross@media-main:~/turtlecoind-ha$ node -v
v12.11.1
drblackross@media-main:~/turtlecoind-ha$ npm -v
6.11.3
drblackross@media-main:~/turtlecoind-ha$

**Comment by brandonlehmann** [comment]
Please try adding:

```bash
export NODE_ENV=production
```

before attempting to start the service

**Comment by brandonlehmann** [comment]
Considered resolved.
