### ISSUE TITLE
Enabling websocket password creates startup error

### ISSUE THREAD

**Issue by fexra** [turtlecoin/turtlecoind-ha#2]
When enabling the webSocketPassword to true by altering the default configurations turtlecoind-ha.js

`  this.webSocketPassword = opts.webSocketPassword || true`

The following error occurs on starting service.js

```js

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type boolean
    at Function.from (buffer.js:222:9)
    at new Buffer (buffer.js:170:17)
    at module.exports (/home/fexra/turtlecoind-ha/node_modules/sha256/lib/nodecrypto.js:14:12)
    at new WebSocket (/home/fexra/turtlecoind-ha/lib/websocket.js:16:21)
    at TurtleCoind._setupWebSocket (/home/fexra/turtlecoind-ha/turtlecoind-ha.js:386:22)
    at TurtleCoind.once (/home/fexra/turtlecoind-ha/turtlecoind-ha.js:70:10)
    at Object.onceWrapper (events.js:272:13)
    at TurtleCoind.emit (events.js:185:15)
    at TurtleCoind.start (/home/fexra/turtlecoind-ha/turtlecoind-ha.js:209:8)
    at Object.<anonymous> (/home/fexra/turtlecoind-ha/service.js:56:8)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

```

**Comment by fexra** [comment]
Ah I see. It would be nice if it follows the same format as walletd-ha - or at least have them follow the same format. I assumed to set it to true and set the pass in turtlecoind-ha in the service file like this:

```js
var daemon = new TurtleCoind({
  rpcPassword: 'pass'
})
```

**Comment by brandonlehmann** [comment]
I’ll give it some thought.  turtlecoind doesn’t have an rpc password so it’s not implemented in the same way. Also, it’s not a password for the rpc - it’s a password for protected events.

**Comment by fexra** [comment]
@brandonlehmann Ah right that makes actually a lot of sense.

**Comment by brandonlehmann** [comment]
@fexra can we close this issue?
